# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

#x#CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n
#x#CONFIG_ZMK_DISPLAY_TICK_PERIOD_MS=10
#x## n = black on white
#x#CONFIG_ZMK_DISPLAY_INVERT=n
#x#
#x## y = show layer status
#x#CONFIG_ZMK_WIDGET_LAYER_STATUS=y
#x#
#x## y = show battery info
#x#CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
#x#
#x## y = show battery info as percentage
#x#CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
#x#
#x## y = show bluetooth status
#x#CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
#x#
#x## y = show word-per-minute
#x#CONFIG_ZMK_WIDGET_WPM_STATUS=n
